id: P010369
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 20:46:19.398736
source_metadata:
  id: bdr:W1KG25530
  title: མི་ཚེའི་འགྲུལ་བཞུད།
  author: ''
  volumes:
    dc31e3f00dc14b1582bd5652d74dd496:
      image_group_id: I1KG25532
      title: ''
      volume_number: 1
      total_pages: 274
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
