id: I4992DCFE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T12:27:16+00:00'
last_modified: '2022-06-08T13:05:22.315288+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25530
  title: མི་ཚེའི་འགྲུལ་བཞུད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    706D:
      image_group_id: I1KG25532
      title: ''
      total_pages: 274
      order: 1
      base_file: 706D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
